// <auto-generated />
using System;
using ApiIntro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiIntro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiIntro.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5468),
                            Title = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5469),
                            Title = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5470),
                            Title = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5471),
                            Title = "Category 4"
                        });
                });

            modelBuilder.Entity("ApiIntro.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5387),
                            Name = "Category 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5389),
                            Name = "Category 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5390),
                            Name = "Category 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 12, 19, 9, 10, 565, DateTimeKind.Local).AddTicks(5390),
                            Name = "Category 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
